### PR TITLE
Fixed regex => grouping issue when tvg-logo was empty.

### PR DESCRIPTION
**Pull request by Nux007**
Fixed regex => grouping issue when tvg-logo was empty.
Fixed utf8 names.
Added icon image also when items are grouped.
Fixed Regex for item name ( group 2 ), sometimes title was inclufing tvg-logo property when a coma was in title.
Added TheTv Db scan for tv shows ( added inside contextual menu of each lists ) 
Retreive overview, fanart and poster for grouped Tv Shows.
Started to implement The Movie DB.

### CODE REVIEW

**Comment by avigdork** [comment]
Thanks, I'll look into this.
About the icon for a group of channels, I need to do another change because there is a different between a group of links to the same channel (show icon) to a group of channels (don't show icon).

**Comment by Nux007** [comment]
No problems, I also started to implement themoviedb and thetvdb for playlists with tvshows and movies to retrieve infos about them...

**Comment by avigdork** [comment]
@Nux007 
Hi.
I made this addon long time ago for personal use and didn't know that it will be so famous.
I'm not going to maintenance it anymore, so you more than welcome to take the ownership on it.

**Comment by Nux007** [comment]
@avigdork 
Hi, if you are sure you want to give me the ownership on it, then no problems ;-)

**Comment by avigdork** [comment]
@Nux007
Yes. I'm sure.
I don't have any time to it anymore. 
Thanks. 

Don't forget to erase the dependant on my repo from addon.xml.  I'm going to take my repo off soon.

**Comment by Nux007** [comment]
Will do ASAP  ;-) thank's

**Comment by avigdork** [comment]
@Nux007 
Thanks.
I saw you add it to your repository and release ver 1.2.1, so I add your repo to mine and release ver 1.2.0.1 so all users will automatically get you upgrade.

**Comment by Nux007** [comment]
Thank's for the PR, I made a too quick commit ;-)

**Pull request closed without merging**
